### ISSUE TITLE
examples/sft/run_peft.sh model load dtype error 

### ISSUE THREAD

**Issue by galtay** [huggingface/peft#1598]
### System Info

peft installed from main
c4c826c0c0dfe06620db8b8adcfa55f22acfed61

- `transformers` version: 4.39.1
- Platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.11.8
- Huggingface_hub version: 0.22.0
- Safetensors version: 0.4.2
- Accelerate version: 0.28.0
- PyTorch version (GPU?): 2.2.1+cu121 (True)
GPU RTX3090

### Who can help?
@pacman100 @younesbelkada 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder
- [ ] My own task or dataset (give details below)

### Reproduction

```shell
CUDA_VISIBLE_DEVICES=0 python examples/sft/train.py \
--seed 100 \
--model_name_or_path "mistralai/Mistral-7B-v0.1" \
--dataset_name "smangrul/ultrachat-10k-chatml" \
--chat_template_format "chatml" \
--add_special_tokens False \
--append_concat_token False \
--splits "train,test" \
--max_seq_len 2048 \
--num_train_epochs 1 \
--logging_steps 5 \
--log_level "info" \
--logging_strategy "steps" \
--evaluation_strategy "epoch" \
--save_strategy "epoch" \
--bf16 True \
--packing True \
--learning_rate 1e-4 \
--lr_scheduler_type "cosine" \
--weight_decay 1e-4 \
--warmup_ratio 0.0 \
--max_grad_norm 1.0 \
--output_dir "mistral-sft-lora" \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 8 \
--gradient_accumulation_steps 8 \
--gradient_checkpointing True \
--use_reentrant True \
--dataset_text_field "content" \
--use_peft_lora True \
--lora_r 8 \
--lora_alpha 16 \
--lora_dropout 0.1 \
--lora_target_modules "all-linear" \
--use_4bit_quantization True \
--use_nested_quant True \
--bnb_4bit_compute_dtype "bfloat16" \
--use_flash_attn True
```

it seems that `--bf16` may be having a strange interaction with the bitsandbytes config
adding 
```
--bnb_4bit_quant_storage_dtype "bfloat16" 
```
allows it to run, but that seems like a hack b/c the default for that is typically `uint8`

### Expected behavior

the example script not producing the following error

```shell
`low_cpu_mem_usage` was None, now set to True since model is quantized.
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in MistralForCausalLM is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
...
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by BenjaminBossan** [comment]
> adding
> 
> ```
> --bnb_4bit_quant_storage_dtype "bfloat16" 
> ```
> 
> allows it to run, but that seems like a hack b/c the default for that is typically `uint8`

I don't think this is a hack, bfloat16 is a legitimate value for that parameter. Note that in the script, it's [float32 by default](https://github.com/huggingface/peft/blob/c4c826c0c0dfe06620db8b8adcfa55f22acfed61/examples/sft/train.py#L42-L44), not uint8.

**Comment by galtay** [comment]
Yea, sorry, "hack" was probably the wrong word. It seems that the default storage type in the bitsandbytes library is `uint8` (e.g. https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/nn/modules.py#L216) and that if someone is quantizing the base model its probable that they would like to use that storage dtype. 

However, using `--bnb_4but_quant_storage_dtype "uint8" produces, 

```
ValueError: Can't instantiate MistralForCausalLM model under dtype=torch.uint8 since it is not a floating point dtype
```

I haven't seen examples of using `bfloat16` or `float16` or `float32` for the bnb storage type but that doesn't mean much! I was wondering if that implies more RAM usage or if the 4bit parameters are efficiently packed into whatever storage dtype is specified.

**Comment by galtay** [comment]
I think maybe, 

`quant_storage_dtype` should default to `uint8` and be passed to bnb_config here (as is already the case)
https://github.com/huggingface/peft/blob/main/examples/sft/utils.py#L107

but it shouldn't be reused when creating the model here 
https://github.com/huggingface/peft/blob/main/examples/sft/utils.py#L133

you can probably set `torch_dtype` to None if a `bnb_config` exists and/or add it to the script args and parse it and/or get it from `--bf16` or --fp16` if they are passed (which currently seem to be ignored)

**Comment by BenjaminBossan** [comment]
Thanks a lot for investigating further. Your suggestion sounds reasonable to me, but I'm not an expert on this matter. Pinging @pacman100 who wrote this script if he thinks that this is a good solution.

**Comment by pacman100** [comment]
Hello @galtay, yes, you are correct, I have fixed this in https://github.com/pacman100/DHS-LLM-Workshop/blob/ca763838b6b87fe9b1d08961ce8b8295f7ecd2b0/chat_assistant/sft/training/utils.py#L148-L155 but forgot to make the same changes in the PEFT example.

**Comment by pacman100** [comment]
I have raised the above PR with the fixes and added @galtay as the co-author. Could you please confirm if this resolves the issue? 

> if the 4bit parameters are efficiently packed into whatever storage dtype is specified

This is the case but I too have observed more memory usage with FP32 dtype.

**Comment by galtay** [comment]
thanks @pacman100 ! i'll do some tests tomorrow
