### ISSUE TITLE
"addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by cd9807** [huggingface/peft#267]
When I loaded my finely tuned llama model for inference, I encountered this error, and the log is as follows:

**Comment by cd9807** [comment]
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.1/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 111
CUDA SETUP: Loading binary /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so...
Loading checkpoint shards: 100%|███████████████████████████████████████████████| 2/2 [00:10<00:00,  5.48s/it]
/home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/generation/utils.py:1384: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cuda, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/HDD2/caidi/cd/code/gpt/llama-docker-playground/alpaca-lora/with_history_generate.py:202 in │
│ <module>                                                                                         │
│                                                                                                  │
│   199                                                                                            │
│   200 if __name__ == "__main__":                                                                 │
│   201 │   question = "你好"                                                                      │
│ ❱ 202 │   answer = evaluate(question)                                                            │
│   203 │   print(answer)                                                                          │
│   204 │   # demo.launch(share=True)# , auth=("royd", "9807")                                     │
│   205                                                                                            │
│                                                                                                  │
│ /home/HDD2/caidi/cd/code/gpt/llama-docker-playground/alpaca-lora/with_history_generate.py:158 in │
│ evaluate                                                                                         │
│                                                                                                  │
│   155 │   │   │   **kwargs,                                                                      │
│   156 │   │   )                                                                                  │
│   157 │   │   with torch.no_grad():                                                              │
│ ❱ 158 │   │   │   generation_output = model.generate(                                            │
│   159 │   │   │   │   input_ids=input_ids,                                                       │
│   160 │   │   │   │   generation_config=generation_config,                                       │
│   161 │   │   │   │   return_dict_in_generate=True,                                              │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/peft/peft_model.py:581 in │
│ generate                                                                                         │
│                                                                                                  │
│   578 │   │   self.base_model.prepare_inputs_for_generation = self.prepare_inputs_for_generati   │
│   579 │   │   try:                                                                               │
│   580 │   │   │   if not isinstance(self.peft_config, PromptLearningConfig):                     │
│ ❱ 581 │   │   │   │   outputs = self.base_model.generate(**kwargs)                               │
│   582 │   │   │   else:                                                                          │
│   583 │   │   │   │   if "input_ids" not in kwargs:                                              │
│   584 │   │   │   │   │   raise ValueError("input_ids must be provided for Peft model generati   │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/autograd/grad_mode. │
│ py:27 in decorate_context                                                                        │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│    29 │                                                                                          │
│    30 │   def _wrap_generator(self, func):                                                       │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/generation/u │
│ tils.py:1500 in generate                                                                         │
│                                                                                                  │
│   1497 │   │   │   │   **model_kwargs,                                                           │
│   1498 │   │   │   )                                                                             │
│   1499 │   │   │   # 13. run beam search                                                         │
│ ❱ 1500 │   │   │   return self.beam_search(                                                      │
│   1501 │   │   │   │   input_ids,                                                                │
│   1502 │   │   │   │   beam_scorer,                                                              │
│   1503 │   │   │   │   logits_processor=logits_processor,                                        │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/generation/u │
│ tils.py:2759 in beam_search                                                                      │
│                                                                                                  │
│   2756 │   │   │                                                                                 │
│   2757 │   │   │   model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)  │
│   2758 │   │   │                                                                                 │
│ ❱ 2759 │   │   │   outputs = self(                                                               │
│   2760 │   │   │   │   **model_inputs,                                                           │
│   2761 │   │   │   │   return_dict=True,                                                         │
│   2762 │   │   │   │   output_attentions=output_attentions,                                      │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/models/llama │
│ /modeling_llama.py:705 in forward                                                                │
│                                                                                                  │
│   702 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return   │
│   703 │   │                                                                                      │
│   704 │   │   # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)    │
│ ❱ 705 │   │   outputs = self.model(                                                              │
│   706 │   │   │   input_ids=input_ids,                                                           │
│   707 │   │   │   attention_mask=attention_mask,                                                 │
│   708 │   │   │   position_ids=position_ids,                                                     │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/models/llama │
│ /modeling_llama.py:593 in forward                                                                │
│                                                                                                  │
│   590 │   │   │   │   │   None,                                                                  │
│   591 │   │   │   │   )                                                                          │
│   592 │   │   │   else:                                                                          │
│ ❱ 593 │   │   │   │   layer_outputs = decoder_layer(                                             │
│   594 │   │   │   │   │   hidden_states,                                                         │
│   595 │   │   │   │   │   attention_mask=attention_mask,                                         │
│   596 │   │   │   │   │   position_ids=position_ids,                                             │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/models/llama │
│ /modeling_llama.py:311 in forward                                                                │
│                                                                                                  │
│   308 │   │   hidden_states = self.input_layernorm(hidden_states)                                │
│   309 │   │                                                                                      │
│   310 │   │   # Self Attention                                                                   │
│ ❱ 311 │   │   hidden_states, self_attn_weights, present_key_value = self.self_attn(              │
│   312 │   │   │   hidden_states=hidden_states,                                                   │
│   313 │   │   │   attention_mask=attention_mask,                                                 │
│   314 │   │   │   position_ids=position_ids,                                                     │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/transformers/models/llama │
│ /modeling_llama.py:212 in forward                                                                │
│                                                                                                  │
│   209 │   ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:       │
│   210 │   │   bsz, q_len, _ = hidden_states.size()                                               │
│   211 │   │                                                                                      │
│ ❱ 212 │   │   query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.   │
│   213 │   │   key_states = self.k_proj(hidden_states).view(bsz, q_len, self.num_heads, self.he   │
│   214 │   │   value_states = self.v_proj(hidden_states).view(bsz, q_len, self.num_heads, self.   │
│   215                                                                                            │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/HDD2/caidi/python/anaconda3/anaconda/lib/python3.8/site-packages/peft/tuners/lora.py:356   │
│ in forward                                                                                       │
│                                                                                                  │
│   353 │   │   │                                                                                  │
│   354 │   │   │   return F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bi   │
│   355 │   │   elif self.r > 0 and not self.merged:                                               │
│ ❱ 356 │   │   │   result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.   │
│   357 │   │   │   if self.r > 0:                                                                 │
│   358 │   │   │   │   result += self.lora_B(self.lora_A(self.lora_dropout(x))) * self.scaling    │
│   359 │   │   │   return result                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

**Comment by younesbelkada** [comment]
Hi @cd9807 
I think that you are running the inference on CPU + half-precision, leading to some operations that are not supported on CPU.
Can you share the full script with us?

**Comment by cd9807** [comment]
@younesbelkada Hi,

**Comment by cd9807** [comment]
@younesbelkada Hi, thank you for replying to my issue. I have seen other issues pointing out that this issue is reasoning on the CPU, but I am reasoning on the GPU, which is what confuses me. Here is my script:

import sys
import time
import os
device = "cuda"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import torch
import transformers
from peft import PeftModel
import gradio as gr
from transformers import GenerationConfig, LlamaForCausalLM, LlamaTokenizer

base_model = "/home/HDD2/caidi/my_model/chinese-llama-hf/"
lora_weights = "/home/HDD2/caidi/my_model/law-chinese-llama-lora/init/"
load_8bit = False



assert (
    "LlamaTokenizer" in transformers._import_structure["models.llama"]
), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git"  # noqa: E501


tokenizer = LlamaTokenizer.from_pretrained(base_model)
if device == "cuda":
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=load_8bit,
        torch_dtype=torch.float16,
        device_map="auto",
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        torch_dtype=torch.float16,
    )
elif device == "mps":
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        device_map={"": device},
        torch_dtype=torch.float16,
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        device_map={"": device},
        torch_dtype=torch.float16,
    )
else:
    model = LlamaForCausalLM.from_pretrained(
        base_model, device_map={"": device}, low_cpu_mem_usage=True
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        device_map={"": device},
    )

# unwind broken decapoda-research config
model.config.pad_token_id = tokenizer.pad_token_id = 0  # unk
model.config.bos_token_id = 1
model.config.eos_token_id = 2

if not load_8bit:
    model.half()  # seems to fix bugs for some users.

model.eval()

def evaluate(
    instruction,
    temperature=0.15,
    top_p=0.7,
    top_k=45,
    num_beams=6,
    max_new_tokens=512,
    **kwargs,
    ):
    if len(instruction) >= max_new_tokens:
        return "历史对话总字符数超出最大长度限制，无法回答！！！"
    inputs = tokenizer(instruction, return_tensors="pt")
    input_ids = inputs["input_ids"].to(device)
    generation_config = GenerationConfig(
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        num_beams=num_beams,
        **kwargs,
    )
    with torch.no_grad():
        generation_output = model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
            max_new_tokens=max_new_tokens,
        )
    s = generation_output.sequences[0]
    output = tokenizer.decode(s)
    answer = output.split("### Output：")[-1].strip()
    torch.cuda.empty_cache()
    model.zero_grad()
    if not answer:
        answer = "对不起，我不太清楚这个问题，我不知道怎么回答。"
    return answer


if __name__ == "__main__":
    question = "### Input：你好\n### Output："
    answer = evaluate(question)
    print(answer)
    # demo.launch(share=True)# , auth=("royd", "9807")

**Comment by cd9807** [comment]
@younesbelkada Hi, thank you for replying to my issue. I have seen other issues pointing out that this issue is reasoning on the CPU, but I am reasoning on the GPU, which is what confuses me. Here is my script:
`import sys
import time
import os
device = "cuda"
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
import torch
import transformers
from peft import PeftModel
import gradio as gr
from transformers import GenerationConfig, LlamaForCausalLM, LlamaTokenizer

base_model = "/home/HDD2/caidi/my_model/chinese-llama-hf/"
lora_weights = "/home/HDD2/caidi/my_model/law-chinese-llama-lora/init/"
load_8bit = False



assert (
    "LlamaTokenizer" in transformers._import_structure["models.llama"]
), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git"  # noqa: E501


tokenizer = LlamaTokenizer.from_pretrained(base_model)
if device == "cuda":
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=load_8bit,
        torch_dtype=torch.float16,
        device_map="auto",
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        torch_dtype=torch.float16,
    )
elif device == "mps":
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        device_map={"": device},
        torch_dtype=torch.float16,
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        device_map={"": device},
        torch_dtype=torch.float16,
    )
else:
    model = LlamaForCausalLM.from_pretrained(
        base_model, device_map={"": device}, low_cpu_mem_usage=True
    )
    model = PeftModel.from_pretrained(
        model,
        lora_weights,
        device_map={"": device},
    )

# unwind broken decapoda-research config
model.config.pad_token_id = tokenizer.pad_token_id = 0  # unk
model.config.bos_token_id = 1
model.config.eos_token_id = 2

if not load_8bit:
    model.half()  # seems to fix bugs for some users.

model.eval()

def evaluate(
    instruction,
    temperature=0.15,
    top_p=0.7,
    top_k=45,
    num_beams=6,
    max_new_tokens=512,
    **kwargs,
    ):
    if len(instruction) >= max_new_tokens:
        return "历史对话总字符数超出最大长度限制，无法回答！！！"
    inputs = tokenizer(instruction, return_tensors="pt")
    input_ids = inputs["input_ids"].to(device)
    generation_config = GenerationConfig(
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        num_beams=num_beams,
        **kwargs,
    )
    with torch.no_grad():
        generation_output = model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
            max_new_tokens=max_new_tokens,
        )
    s = generation_output.sequences[0]
    output = tokenizer.decode(s)
    answer = output.split("### Output：")[-1].strip()
    torch.cuda.empty_cache()
    model.zero_grad()
    if not answer:
        answer = "对不起，我不太清楚这个问题，我不知道怎么回答。"
    return answer


if __name__ == "__main__":
    question = "### Input：你好\n### Output："
    answer = evaluate(question)
    print(answer)

`

**Comment by cd9807** [comment]
Okay, I found a problem, my GPU is broken, Thanks~
