### ISSUE TITLE
OOM during saving checkpoint

### ISSUE THREAD

**Issue by thepowerfuldeez** [huggingface/peft#447]
Hi! I am using this [script](https://github.com/lvwerra/trl/blob/main/examples/stack_llama/scripts/supervised_finetuning.py) to fine-tune LLM using LORA using 8-bit version of a base model.

GPU is filled 55GB/80GB but when `_save_checkpoint` triggers inside HuggingFace Trainer, specifically when it invokes `self.model.state_dict()` training crashes with OOM.

Does LoraModel's `state_dict` gathers state dict of a whole model? How to save checkpoint in that case?

```
Traceback (most recent call last):
  File ".../supervised_finetuning.py", line 213, in <module>
    main(args)
  File ".../supervised_finetuning.py", line 201, in main
    run_training(args, train_dataset, eval_dataset)
  File ".../supervised_finetuning.py", line 178, in run_training
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2006, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2291, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2348, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2830, in save_model
    self._save(output_dir)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2873, in _save
    state_dict = self.model.state_dict()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1833, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1830, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/nn/modules.py", line 268, in _save_to_state_dict
    self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)
  File "/usr/local/lib/python3.8/dist-packages/bitsandbytes/autograd/_functions.py", line 96, in undo_layout
    outputs = torch.empty_like(tensor)  # note: not using .index_copy because it was slower on cuda
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB. GPU 0 has a total capacty of 79.35 GiB of which 64.19 MiB is free. Process 36029 has 79.28 GiB memory in use. Of the allocated memory 74.14 GiB is allocated by PyTorch, and 3.88 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by thepowerfuldeez** [comment]
might be related 
https://github.com/tloen/alpaca-lora/issues/344

**Comment by thepowerfuldeez** [comment]
I could confirm that it works with not the lastest bitsandbytes (0.38.1)
`pip install bitsandbytes==0.37.2` solved my problem as a temporary fix
