### ISSUE TITLE
OutOfMemoryError: CUDA out of memory. Is it a matter of data size?

### ISSUE THREAD

**Issue by dsj96** [huggingface/peft#525]
## Error log & Expected behavior
When I run [mt0-xxl(13B)](https://huggingface.co/bigscience/mt0-xxl) on 2 V100(32 G), batch size=2, num_beams=5 and 12,000 pieces of train data, The program can run successfully.
However, when I change to 372,000 pieces of  train data and run it on  4 V100. I met the `CUDA out of memory` problem.
The main difference is the data size.  Is it a matter of data size?
ZeRO-3 should automatically collect and partition model parameters  during the forward and backward passes. According to ZeRO-stage-3, when I only add data size, I should have no problem running on 4 V100.

Could you give me some suggestions about  partition model parameters in a more controllable and reasonable way? 
```
  1%|          | 307/46384 [40:22<104:17:25,  8.15s/it]
  1%|          | 307/46384 [40:22<104:17:43,  8.15s/it]
  1%|          | 307/46384 [40:22<104:18:59,  8.15s/it]
  1%|          | 307/46384 [40:22<104:20:38,  8.15s/it]
  1%|          | 307/46384 [40:26<101:10:22,  7.90s/it]
Traceback (most recent call last):
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 495, in <module>
    main()
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 293, in main
    outputs = model(**batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/engine.py", line 1695, in forward
    loss = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/peft/src/peft/peft_model.py", line 859, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1057, in forward
    layer_outputs = layer_module(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 556, in forward
    self_attention_outputs = self.layer[0](
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 461, in forward
    attention_output = self.SelfAttention(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 420, in forward
    attn_weights = nn.functional.softmax(scores.float(), dim=-1).type_as(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1843, in softmax
    ret = input.softmax(dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 340.00 MiB (GPU 1; 31.75 GiB total capacity; 27.06 GiB already allocated; 335.75 MiB free; 30.25 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 106 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 108 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 109 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 107) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 908, in launch_command
    deepspeed_launcher(args)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/commands/launch.py", line 647, in deepspeed_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
```

## accelerate config
./ds_zero3_config/ds_zero3_cpu_gpu4.yaml
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
## run cmd
```
model=mt0-xxl
config_file=./ds_zero3_config/ds_zero3_cpu_gpu4.yaml
dataset_name='./data/opus-100/opus-100-corpus/v1.0/opus_train_dev_tst/opus_dev_dev_tst_add_task'
raw_dataset_name=opus_dev_dev_tst_add_task
r=8
lora_alpha=32
lora_dropout=0.1
text_column=SRC
label_column=TGT
lr=2e-5
num_epochs=3
batch_size=2
src_max_length=256
GPU=True
max_new_tokens=256
num_beams=5
no_repeat_ngram_size=1
save_interval=10000
model_name_or_path=./pre_trained_model/$model

output_dir=./trained_checkpoint/model-$model-raw_dataset_name-$raw_dataset_name-lr-$lr-num_epochs-$num_epochs-batch_size-$batch_size-src_max_length-$src_max_length-max_new_tokens-$max_new_tokens-num_beams-$num_beams-save_interval-$save_interval
echo $output_dir
accelerate launch --config_file=$config_file examples/mt0_peft_lora_ds_zero3_offload.py --model_name_or_path=$model_name_or_path --dataset_name=$dataset_name\
                    --r=$r --lora_alpha=$lora_alpha --lora_dropout=$lora_dropout --text_column=$text_column --label_column=$label_column \
                    --lr=$lr --num_epochs=$num_epochs --batch_size=$batch_size --save_interval=$save_interval\
                    --src_max_length=$src_max_length --GPU  --output_dir=$output_dir --max_new_tokens=$max_new_tokens --num_beams=$num_beams
```

## python script
examples/mt0_peft_lora_ds_zero3_offload.py
Model loading and training are modified from [peft_lora_seq2seq_accelerate_ds_zero3_offload.py](https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py)
```
model = AutoModelForSeq2SeqLM.from_pretrained(model_name_or_path)
```

**Comment by dittops** [comment]
Using model.gradient_checkpointing_enable() before loading LoRA config resolved the issue for me. But I'm still testing if this has any impact on performance or result quality.

**Comment by dsj96** [comment]
> Using model.gradient_checkpointing_enable() before loading LoRA config resolved the issue for me. But I'm still testing if this has any impact on performance or result quality.

Thank you for your advice.
when I add the `model.gradient_checkpointing_enable()`  before loading LoRA config, 
```python
    # creating model
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name_or_path, torch_dtype="auto", device_map="auto")
    if not args.inference_mode:
        model.gradient_checkpointing_enable()
        model = get_peft_model(model, peft_config)
        model.print_trainable_parameters()
...
    # training
    for epoch in range(num_epochs):
        with TorchTracemalloc() as tracemalloc:
            model.train()
            accelerator.print('train epoch{}'.format(epoch))
            total_loss = 0
            for step, batch in enumerate(tqdm(train_dataloader)):
                # pdb.set_trace()
                outputs = model(**batch, use_cache=False)
                loss = outputs.loss
                total_loss += loss.detach().float()
                accelerator.backward(loss)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()
```
I met the following problem,
```
/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
  0%|                                                                                                                                                                           | 0/92767 [00:08<?, ?it/s]
  0%|                                                                                                                                                                           | 0/92767 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 497, in <module>
    main()
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 298, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1677, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
Traceback (most recent call last):
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 497, in <module>
    main()
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 298, in main
    accelerator.backward(loss)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1677, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/engine.py", line 1816, in backward
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/engine.py", line 1816, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/zero/stage3.py", line 1923, in backward
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/zero/stage3.py", line 1923, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward
    scaled_loss.backward(retain_graph=retain_graph)
      File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
scaled_loss.backward(retain_graph=retain_graph)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
I tried some solutions, like change `outputs = model(**batch, use_cache=False)` to  `outputs = model(**batch)`, but they didn't work.

**Comment by dittops** [comment]
Can you try model.enable_input_require_grads() along with gradient checkpointing?

```
model.gradient_checkpointing_enable()
model.enable_input_require_grads()
```

**Comment by dsj96** [comment]
YES, I tested this modification yesterday. It works for me. 
Thank you again! : )

**Comment by dsj96** [comment]
After I add 
```python
model.gradient_checkpointing_enable()
model.enable_input_require_grads()
```
in the script. Programs can train longer to 26%. But after that, whether I increase or decrease the batch size, Increase or decrease the number of GPU v100 (32 G), the program always trains to 26% and terminates. This makes me very confused. Although this issue may be closed, if you have any ideas, please feel free to contact me and  let me know at any time!
thanks!!!

###  bug repo1
```bash
 26%|██▌       | 1488/5798 [7:44:21<22:06:08, 18.46s/it]
 26%|██▌       | 1488/5798 [7:44:22<22:25:03, 18.72s/it]
Traceback (most recent call last):
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 509, in <module>
    main()
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 303, in main
    outputs = model(**batch, use_cache=False) # dsj
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/engine.py", line 1695, in forward
    loss = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/peft/src/peft/peft_model.py", line 859, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1044, in forward
    layer_outputs = checkpoint(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1040, in custom_forward
    return tuple(module(*inputs, use_cache, output_attentions))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 556, in forward
    self_attention_outputs = self.layer[0](
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 461, in forward
    attention_output = self.SelfAttention(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 420, in forward
    attn_weights = nn.functional.softmax(scores.float(), dim=-1).type_as(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 17.54 GiB (GPU 1; 31.75 GiB total capacity; 22.98 GiB already allocated; 5.83 GiB free; 24.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## bug repo2
```bash
26%|██▌       | 2976/11596 [8:43:40<24:54:06, 10.40s/it]
 26%|██▌       | 2976/11596 [8:43:40<25:16:50, 10.56s/it]
Traceback (most recent call last):
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 509, in <module>
    main()
  File "examples/mt0_peft_lora_ds_zero3_offload.py", line 303, in main
    outputs = model(**batch, use_cache=False) # dsj
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/userhome/dsj/deepspeed/deepspeed/runtime/engine.py", line 1695, in forward
    loss = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/peft/src/peft/peft_model.py", line 859, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1044, in forward
    layer_outputs = checkpoint(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 1040, in custom_forward
    return tuple(module(*inputs, use_cache, output_attentions))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 556, in forward
    self_attention_outputs = self.layer[0](
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 461, in forward
    attention_output = self.SelfAttention(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/userhome/dsj/transformers/src/transformers/models/mt5/modeling_mt5.py", line 420, in forward
    attn_weights = nn.functional.softmax(scores.float(), dim=-1).type_as(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1843, in softmax
    ret = input.softmax(dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.77 GiB (GPU 3; 31.75 GiB total capacity; 21.87 GiB already allocated; 7.38 GiB free; 22.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by vineetsharma14** [comment]
Hello There,

I used these 2 lines

```
model.gradient_checkpointing_enable()
model.enable_input_require_grads()
```


Training Args:

per_device_train_batch_size=1,
gradient_accumulation_steps=4

On RTX 3090 24GB GPU.


But it does not resolve the issue. 

The GPU VRAM utilisation gradually increases and then I get CUDA OOM error.

Any suggestions of how can I resolve this.



Thanks for the help.

**Comment by anonymoususerr1** [comment]
I am havig exactly the same issue. Any idea how to resolve this?
